### ISSUE TITLE
Bad random numbers, or other major bias.

### ISSUE THREAD

**Issue by Meerkov** [PetterS/monte-carlo-tree-search#2]
To reproduce:
Load up connect four.

Look at the first move percentages:

Move: 0 ( 2% visits) (50% wins)
Move: 1 ( 3% visits) (52% wins)
Move: 2 ( 6% visits) (55% wins)
Move: 3 (80% visits) (60% wins)
Move: 4 (5% visits) (3% wins)
Move: 5 (3% visits) (2% wins)
Move: 6 (2% visits) (1% wins)

Since the board is symmetric and empty for the first move, I see no reason why the AI moving on the left side of the board (move 0,1,2) should have >50% win rate, but moves on the right side of the board (move 4,5,6) would have ~0% win rate. 

Keep in mind they have nearly the same percentage of total visits, so they shouldn't be that much different.

**Comment by PetterS** [comment]
Indeed. This certainly warrants investigation.

**Comment by PetterS** [comment]
It is an output error: https://github.com/PetterS/monte-carlo-tree-search/blob/master/mcts.h#L434
wins is divided by best_visits, which changes in the loop.

**Comment by PetterS** [comment]
Thanks a lot for reporting this! :+1:
