### ISSUE TITLE
MCTS selects moves which are clearly not the best

### ISSUE THREAD

**Issue by Meerkov** [PetterS/monte-carlo-tree-search#3]
To reproduce:
Load Connect Four.
In connect_four.cpp, reduce the number of iterations of player 1 to approximately 100.
Change goal of game to be connect 2 by editing the scoring function (should be easily provable that first player wins on move 3).

Some moves maybe have 100% win rate, but these are not the moves chosen. Instead, the move which was visited the most is picked.

This is the wrong metric to play by, and is a serious mistake.

**Comment by PetterS** [comment]
Off the top of my head: just because a node has 100% win rate does not mean it is guaranteed to be the best.

One node could have a single randomized game played, which was won. Another could have a million games played, with a 99% win rate. I’d rather pick the second one.

**Comment by Meerkov** [comment]
I might argue that there is a problem with the way the node to explore next is selected, if a node with a 100% win rate doesn't get explored the most.

**Comment by Meerkov** [comment]
Ah yes, here it is:
std::sqrt(2.0 * std::log(double(this->visits + 1)) / child->visits);

This is taking the sqrt of the wrong thing.
The numerator should be the log of the _total_ number of visits of the simulation, not the number of the parent node.

**Comment by Meerkov** [comment]
Ok well... Maybe it's right : )
But what about removing the +1 from (this->visits). It seems strange.

child->UCT_score = double(child->wins) / double(child->visits) +
				std::sqrt(2.0 * std::log(double(this->visits +1)) / child->visits);

**Comment by PetterS** [comment]
Yes, a node with 100% win rate should definitely be explored more, and it should be with more iterations.

You are correct that the +1 looks strange. It was introduced in c8095adfa581871f8f96f7de67d761699c7a2ff7 and I don’t remember why. If the node does not have any visits (edge case), the child should not have any either, so the computation still fails.

Let’s remove it.
