### ISSUE TITLE
MCTS optimizes for the wrong thing

### ISSUE THREAD

**Issue by Meerkov** [PetterS/monte-carlo-tree-search#4]
This came up in a previous bug, but I think I have to press this issue. This is subtle, but I think it's important.

The final action chosen needs to be the action with the highest win rate, not the action which was visited the most.

It seems obvious, but when you are playing a game you are interested in the action that gives you the highest win rate, not optimizing for the UCT function which is just a tool to help search the tree. Some visits are going to be due to obligation to **explore**, not because it's actually a good action to take. Most of the time, the action with the most visits, and the action with the highest value, will both be the same. The exception is when you run a low number of iterations.

See slide 13 of this PDF which you can see at the bottom says the action to select is the action with the highest value. The search is trying to maximize value, not visits.
http://scalab.uc3m.es/~seminarios/seminar11/slides/lucas2.pd

**Comment by PetterS** [comment]
The reference implementation at http://mcts.ai/code/python.html uses number of visits.

The correct thing to do from a Bayesian perspective would be to use Beta distributions, I guess. That would be (#wins + 1) / (#total + 2).

**Comment by Meerkov** [comment]
Well, my problem is just as much with the original implementation as this one which is based on it.

(wins/visits) is exactly what I'm suggesting. That's the number the search is attempting to optimize, so that's what should be selected at the end.

In addition, since this is using root parallelization, it exaserbates the probability of ignoring large portions of work.

For example, say you have 8 threads, and each thread is running simulations. One of those threads discovers a line of play which can provide ~60% win rate. Each of the other 7 threads discovers a (different) move, which provides ~40% win rate.

When you sum together the different search trees, the probability of choosing the 60% win rate **should** be 100%, because you should use (wins/visits) and notice that this option is much better. Instead you are checking visits, but some of those threads may not have searched the 60% win rate path as heavily as some of the 40% win rate paths because the ordering of the random paths might have provided more successes towards the beginning of the search, giving it a false impression of goodness that was disproved by the end of the search, especially in conjunction with the other trees.

**Comment by PetterS** [comment]
> (wins/visits) is exactly what I'm suggesting.

That would not be quite correct. (wins + 1) / (visits + 2) would be correct from a Bayesian perspective. Let’s say we have two options, one of which was observed to win 1 out of 1 times, and the other winning 9999 out of 10000 times. Which one would you want to pick? I’d choose the second one.

I’ll probably make this change pretty soon.

**Comment by Meerkov** [comment]
Sure, that's a reasonable metric to optimize.

**Comment by undersun81** [comment]
mcts.h:422 line has a misleading comment about choosing by max visits after this change.

**Comment by PetterS** [comment]
You’re right. I fixed it.

**Comment by carlosgmartin** [comment]
@Meerkov @PetterS Are you sure about this? [This paper](https://www.aaai.org/Papers/AIIDE/2008/AIIDE08-036.pdf) says

> The game action finally executed by the program in the actual game, is the one corresponding to the child which was explored the most.

But the [original UCT paper](https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.102.1296) says `bestAction`. In general, I've seen conflicting answers to this.

>

**Comment by PetterS** [comment]
The most explored child and the best child should hopefully be the same?

**Comment by Meerkov** [comment]
Within a single search tree, yes, the most explored should be the best answer. My intuition is that when you have root parallelization, it could result in a case where one of the threads finds a better answer by chance. I'd recommend finding a paper which discusses paralleization techniques of MCTS, since the original paper didn't discuss the modifications you might need to make.

In either case, using (wins+1)/(visits+2) does not seem like it would give you a worse answer that pure visits.

**Comment by carlosgmartin** [comment]
There's a question on the AI Stack Exchange about this: https://ai.stackexchange.com/questions/16905/mcts-how-to-choose-the-final-action-from-the-root.

**Comment by Meerkov** [comment]
I think the short answer is: In the 13 years since the original UCT paper was written, people have tried different techniques to guide the result. I'd suggest that the only way to be confident that one is better than another is to simply try it out on a meaty game like Go, which you can be sure you won't be able to search the entire space for. Do some experiments and find out which works best for your usecase.

It's no guarantee it's the best choice for everything, but might highlight if one decision method works better than another for root-parallelization in these types of games.
