### ISSUE TITLE
cannot run project on visual studio 2017

### ISSUE THREAD

**Issue by Elad-Lavie** [PetterS/monte-carlo-tree-search#8]
Hi,
We are a group of EE researchers, trying to implement a new variation of alphago zero.
while looking for a fast implementation of mcts-go, we have encountered in your work.
unfortunately, this project doesn't seems to work on VC 2017. 
can you please help up make this project compatible?

to reproduce:
File->Open->Cmake
**error:**

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
>   The C compiler "C:/Program Files (x86)/Microsoft Visual
>   Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe" is
>   not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>    Change Dir: C:/Users/eladl/CMakeBuilds/c47051df-67e5-8834-a0d2-03ff8e47aa7b/build/x86-Debug/CMakeFiles/CMakeTmp
> 
>   
> 
>   Run Build
>   Command:"C:/PROGRA\~2/MIB055\~1/2017/COMMUN\~1/Common7/IDE/COMMON\~1/MICROS~1/CMake/Ninja/ninja.exe"
>   "cmTC_bc256"
> 
>   [1/2] Building C object CMakeFiles\cmTC_bc256.dir\testCCompiler.c.obj
> 
>   [2/2] Linking C executable cmTC_bc256.exe
> 
>   FAILED: cmTC_bc256.exe 
> 
>   cmd.exe /C "cd .  && "C:\Program Files (x86)\Microsoft Visual
>   Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
>   -E vs_link_exe --intdir=CMakeFiles\cmTC_bc256.dir --manifests --
>   C:\PROGRA\~2\MIB055\~1\2017\COMMUN\~1\VC\Tools\MSVC\1411\~1.255\bin\Hostx86\x86\link.exe
>   /nologo CMakeFiles\cmTC_bc256.dir\testCCompiler.c.obj /out:cmTC_bc256.exe
>   /implib:cmTC_bc256.lib /pdb:cmTC_bc256.pdb /version:0.0 /machine:X86 /debug
>   /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib
>   winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
>   advapi32.lib && cd ."
> 
>   The system cannot find the path specified.
> 
> 
>   ninja: build stopped: subcommand failed.
> 
>   
> 
>   
> 
>   CMake will not be able to correctly generate this project.		C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake	51
>

**Comment by PetterS** [comment]
I can confirm it works with Visual Studio 2017. 

I am not sure how you are calling CMake, but don’t use Ninja with Visual Studio. Instead generate a Visual Studio solution, preferably with the CMake GUI. There is no manual configuration required; just press "Configure" and then "Generate" and you are ready!
